create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp text not null,
  full_name text not null,
  unit text not null,
  student_id text not null,
  confirmed text not null default 'Có',
  constraint attendance_student_id_key unique (student_id)
);

alter table public.attendance enable row level security;

-- App dung service_role key o server nen van doc/ghi duoc khi RLS bat.
-- Khong dua service_role key vao frontend.
