create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp text not null,
  full_name text not null,
  unit text not null,
  student_id text not null,
  confirmed text not null default 'Có',
  constraint attendance_student_id_key unique (student_id)
);

alter table public.attendance enable row level security;

drop policy if exists "attendance anon select" on public.attendance;
drop policy if exists "attendance anon insert" on public.attendance;
drop policy if exists "attendance anon delete" on public.attendance;

create policy "attendance anon select"
on public.attendance
for select
to anon
using (true);

create policy "attendance anon insert"
on public.attendance
for insert
to anon
with check (true);

create policy "attendance anon delete"
on public.attendance
for delete
to anon
using (true);

-- Neu dung SUPABASE_SERVICE_ROLE_KEY tren server thi co the khong can cac policy anon.
-- Khong dua service_role key vao frontend.
